services:
  justify-api:
    build: .
    container_name: justify-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
